### ISSUE TITLE
How do we re-mapping environment variables when we execute commands?

### ISSUE THREAD

**Issue by samnang** [m-mizutani/zenv#8]
First, thanks for the great little tool to help with secure environment variables.

Let's say I have a simple program that depends on an environment variable:

```js
import "dotenv/config";

console.log(process.env.AWS_SECRET_ACCESS_KEY)
```

And I have multiple accounts to switch, so I store those in the secret:

```shell
$ zenv secret write @aws-account ACCOUNT1_AWS_SECRET_ACCESS_KEY
Value: # no echo
$ zenv secret write @aws-account ACCOUNT2_AWS_SECRET_ACCESS_KEY
Value: # no echo
```

When I run the program, I would like to be able to switch between the accounts with a few of the following options, but none of them work:
1. Create `.env` that has `AWS_SECRET_ACCESS_KEY=$ACCOUNT1_AWS_SECRET_ACCESS_KEY`.
2. Replace values in arguments: `zenv @aws-account AWS_SECRET_ACCESS_KEY=%ACCOUNT1_AWS_SECRET_ACCESS_KEY ts-node script.ts`
3. Execute command in `.env` with ``AWS_SECRET_ACCESS_KEY=`echo $ACCOUNT1_AWS_SECRET_ACCESS_KEY` ``

One way I tried it works, we could use different namespace for different accounts, but it will be inconvenient when we have different secrets in different credentials for other purposes, and we want to load them as well to be able to run the program.

Do you have any suggestions?

**Comment by m-mizutani** [comment]
@samnang Thank you for your feedback. Previously I also considered about a remapping feature. It would be useful, but I concerned to increase complication of mapping logic for users and did not implement it.

Then, I would like to clarify your use case at first. Could you answer following questions?

- How about use multiple namespaces (e.g. `@aws-account1` and `@aws-account2`) for accounts. Or could you give me your use case that multiple namespaces does't work well or isn't convenient?
- If you want use not also multiple account keys but also common secret value (e.g. github personal access token), how about mixing multiple namespace? You can mix environment variables from multiple namespaces by `zenv @aws-account @github your_command`. Or could you give me an inconvenient case?

**Comment by samnang** [comment]
@m-mizutani Thanks for your response. I could see the reason why you didn't implement it from the beginning. Here are a few reasons that I thought they might not be convenient when we use multiple namespaces in this context:

* When we work with multiple people in the team, variable names might not match what we want to store personally in the local.
* Usually in one application, we depend on many environment variables for different services, so we have to specify them all when we run it: `zenv @postgres @aws-account @logging @monitoring @other-services command`.

Here are a few projects that have similar feature that I found it:
https://github.com/vlucas/phpdotenv#nesting-variables
https://github.com/motdotla/dotenv-expand

**Comment by m-mizutani** [comment]
@samnang Thank you for your comment. I understood your use case and let me consider how to implement a remapping feature. Please give me a minute.

**Comment by m-mizutani** [comment]
@samnang I implemented a feature to replace `%` prefix value with existing other environment variable. You can do like following with `%ACCOUNT1_AWS_SECRET_ACCESS_KEY` instead of `$ACCOUNT1_AWS_SECRET_ACCESS_KEY`

> 1. Create `.env` that has `AWS_SECRET_ACCESS_KEY=$ACCOUNT1_AWS_SECRET_ACCESS_KEY`.


It has been released as v0.1.2

**Comment by samnang** [comment]
@m-mizutani I have tested, it worked as expected 👏 Thanks for taking time to implement this ❤️

One small thing, I noticed you forgot to update the version number here for the cli output. It still says it's `0.1.0`: https://github.com/m-mizutani/zenv/blob/29ee1bbdfb36caaceb024550e4f3de38b71b7267/pkg/domain/model/const.go#L6

**Comment by samnang** [comment]
One quick question, when I use a tool `aws-vault` with keychain as their backend. It usually pops up and asks me to enter a password to unlock their keychain. I believe they create a custom keychain with a different password from the login. I might be wrong, but I feel it's a bit safer, so other programs cannot read the values directly without confirming with the password to unlock it first. What do you think?

<img width="483" alt="image" src="https://user-images.githubusercontent.com/131172/184471116-0f46503c-0680-4a98-9abe-0aa55a2a7a7f.png">

**Comment by m-mizutani** [comment]
@samnang Thank you for an interesting comment. The original concept of `zenv` secret feature is "safer than plaintext credential" and I don't think to change `zenv` with always password required model (`aws-vault` model) for now. However I think it has worth to consider implementation as option. Let me consider to implement it when I have time.
